DATABASE_URL = "your_database_url_here"
LLM_API_KEY = "your_llm_api_key_here"
VECTOR_DB_URL = "your_vector_database_url_here"
DEFAULT_NEIGHBORHOOD = "default_neighborhood"
DEFAULT_PRICE_RANGE = (100000, 500000)
DEFAULT_BEDROOMS = 3
DEFAULT_BATHROOMS = 2
DEFAULT_HOUSE_SIZE = 1500

def get_settings():
    return {
        "DATABASE_URL": DATABASE_URL,
        "LLM_API_KEY": LLM_API_KEY,
        "VECTOR_DB_URL": VECTOR_DB_URL,
        "DEFAULT_NEIGHBORHOOD": DEFAULT_NEIGHBORHOOD,
        "DEFAULT_PRICE_RANGE": DEFAULT_PRICE_RANGE,
        "DEFAULT_BEDROOMS": DEFAULT_BEDROOMS,
        "DEFAULT_BATHROOMS": DEFAULT_BATHROOMS,
        "DEFAULT_HOUSE_SIZE": DEFAULT_HOUSE_SIZE,
    }